config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index show edit update destroy] do
    resources :debit_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
    resources :checking_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
    resources :credit_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new show]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
  end

  # post :liquid_installment, controller: :transactions
  post '/installments/:id' => 'installments#liquid', as: 'liquid'
  resources :categories, only: %i[index new create]
  devise_for :users, path: 'session'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/credit_account.rb
# frozen_string_literal: true

# Credit Accounts Model
class CreditAccount < ApplicationRecord
  belongs_to :user
  has_many :transactions, as: :origin, dependent: :destroy

  validates :currency, inclusion: { in: %w[USD CLP] }
  validates :liquid_balance, numericality: { less_than_or_equal_to: 0 },
                             presence: true
  validates :illiquid_balance, numericality: { less_than_or_equal_to: 0 },
                               presence: true
  validates :credit_limit, numericality: { less_than_or_equal_to: 0 },
                           presence: true
  validate :credit_limit_lower_than_balances

  def credit_limit_lower_than_balances
    if liquid_balance < credit_limit
      errors[:base] << 'Balance liquido no puede ser menor al cupo asignado'
    elsif illiquid_balance < credit_limit
      errors[:base] << 'Balance no liquido no puede ser menor al cupo asignado'
    else
      true
    end
  end
end

app/controllers/credit_accounts_controller.rb
# frozen_string_literal: true

# CreditAccount Controller
class CreditAccountsController < ApplicationController
  before_action :set_user
  before_action :require_permission
  before_action :require_ownership_permission, only: %i[show]

  # GET /users/:user_id/credit_accounts/new
  def new
    @account = CreditAccount.new
  end

  # POST /users/:user_id/debit_accounts
  def create
    @account = CreditAccount.new(account_params)
    @account.user = @user
    if @account.save
      redirect_to @user, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def show
    @transactions = @account.transactions
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  # Only allow a list of trusted parameters through.
  def account_params
    params.require(:credit_account).permit(:currency, :liquid_balance,
                                           :credit_limit)
  end

  def require_permission
    is_admin = user_signed_in? && current_user.admin
    correct_user = user_signed_in? && current_user == @user
    has_permission = is_admin || correct_user
    notice = 'You don\'t have the permissions to do that'

    redirect_to root_path, notice: notice unless has_permission
  end

  def require_ownership_permission
    @account = CreditAccount.find(params[:id])
    is_admin = user_signed_in? && current_user.admin
    is_account_owner_user = @account.user == @user
    has_permission = is_admin || is_account_owner_user
    notice = 'You don\'t have the permissions to do that'

    redirect_to root_path, notice: notice unless has_permission
  end
end

app/helpers/credit_accounts_helper.rb
# frozen_string_literal: true

# Credit Accounts Helper
module CreditAccountsHelper
end

app/views/credit_accounts/_form.html.erb
<%= form_with(model: [user, account], local: true) do |form| %>
  <% if account.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(account.errors.count, 'error') %> prohibited this account from being saved:</h2>

      <ul>
        <% account.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_box">
    <div class="form-group">
      <%= form.label :liquid_balance %>
      <%= form.number_field :liquid_balance, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :currency %>
      <%= form.select :currency, %w[CLP USD], {}, { class: 'form-control' } %>
    </div>

    <div class="actions">
      <%= form.submit 'Create credit account', class: 'btn btn-primary' %>
    </div>
    <br>
  </div>
<% end %>

app/views/credit_accounts/new.html.erb
<h2>New Credit Account</h2>
<hr>

<%= render 'form', account: @account, user: @user %>

<%= link_to 'Back', user_path(@user), type: 'button', class: 'btn btn-dark' %>

app/views/credit_accounts/show.html.erb
<h2>Credit Account <%= @account.id %> </h2>
<hr>

<h5>Liquid balance <%= @account.liquid_balance %> </h5>
<h5>Illiquid balance <%= @account.illiquid_balance %> </h5>
<% if @account.instance_of? CreditAccount %>
  <h5>Credit limit <%= @account.credit_limit %> </h5>
<% end %>
<div>
  <h2>Transactions </h2>

  <table class="table">
  <thead class="thead-light">
    <tr>
      <th>Monto</th>
      <th>Descripcion</th>
      <th>Divisa</th>
      <th>Categoria</th>
      <th>Status</th>
      <th>Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |t| %>
      <tr>
        <td><%= t.amount %></td>
        <td><%= t.description %></td>
        <td><%= t.currency %></td>
        <td><%= t.category.name %></td>
        <td>
          <% if t.status %>
            Liquidada
          <% else %>
            No liquidada
          <% end %>
        </td>
        <td><%= link_to('Revisar cuotas', user_credit_account_transaction_path(@account.user, @account, t)) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New transaction', new_user_credit_account_transaction_path(@user, @account), type: 'button', class: 'btn btn-primary' %>
<br><br>
<%= link_to 'Transfer to another account', user_credit_account_transfer_path(@user, @account), type: 'button', class: 'btn btn-primary' %>
</div>
<hr>

<%= link_to 'Back', user_path(@user), type: 'button', class: 'btn btn-dark' %>