config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index show edit update destroy] do
    resources :debit_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
    resources :checking_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
    resources :credit_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new show]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
  end

  # post :liquid_installment, controller: :transactions
  post '/installments/:id' => 'installments#liquid', as: 'liquid'
  resources :categories, only: %i[index new create]
  devise_for :users, path: 'session'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

# Users Model
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

  has_many :debit_accounts, dependent: :nullify
  has_many :checking_accounts, dependent: :nullify
  has_many :credit_accounts, dependent: :nullify
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# User Controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_permission, only: %i[edit update]
  before_action :require_admin, only: %i[index destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show; end

  # GET /users/1/edit
  def edit; end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:email, :password)
  end

  def require_permission
    is_admin = user_signed_in? && current_user.admin
    correct_user = user_signed_in? && current_user == @user
    has_permission = is_admin || correct_user
    notice = 'You don\'t have the permissions to do that'

    redirect_to root_path, notice: notice unless has_permission
  end

  def require_admin
    is_admin = user_signed_in? && current_user.admin
    notice = 'You don\'t have the permissions to do that'

    redirect_to root_path, notice: notice unless is_admin
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Users Helper
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(user.errors.count, 'error') %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_box">

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit 'Update user', class: 'btn btn-primary' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<h2>Edit Profile</h2>
<hr>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to 'Sign Up', new_user_registration_path %>
    <%= link_to 'Log In', new_user_session_path %>
<% end %>

app/views/users/show.html.erb
<h2>My accounts</h2>
<hr>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<div class="debit">
  <h2>Cuentas de Debito </h2>

  <table class="table">
  <thead class="thead-light">
    <tr>
      <th>Nro de Cuenta</th>
      <th>Saldo Liquido</th>
      <th>Saldo No Liquido</th>
      <th>Divisa</th>
      <th>Ver Transacciones</th>
    </tr>
  </thead>

  <tbody>
    <% @user.debit_accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <td><%= account.liquid_balance %></td>
        <td><%= account.illiquid_balance %></td>
        <td><%= account.currency %></td>
        <td><%= link_to 'Account transactions', user_debit_account_path(@user, account) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nueva cuenta de débito', new_user_debit_account_path(@user), type: 'button', class: 'btn btn-primary' %>
<br><br><hr>

</div>

<div class="checking">
  <h2>Cuentas Corriente </h2>

  <table class="table">
  <thead class="thead-light">
    <tr>
      <th>Nro de Cuenta</th>
      <th>Saldo Liquido</th>
      <th>Saldo No Liquido</th>
      <th>Divisa</th>
      <th>Ver Transacciones</th>
    </tr>
  </thead>

  <tbody>
    <% @user.checking_accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <td><%= account.liquid_balance %></td>
        <td><%= account.illiquid_balance %></td>
        <td><%= account.currency %></td>
        <td><%= link_to 'Account transactions', user_checking_account_path(@user, account) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nueva cuenta corriente', new_user_checking_account_path(@user), type: 'button', class: 'btn btn-primary' %>
<br><br><hr>

</div>

<div class="credit">
  <h2>Cuentas de Credito </h2>

  <table class="table">
  <thead class="thead-light">
    <tr>
      <th>Nro de Cuenta</th>
      <th>Saldo Liquido</th>
      <th>Saldo No Liquido</th>
      <th>Divisa</th>
      <th>Ver Transacciones</th>
    </tr>
  </thead>

  <tbody>
    <% @user.credit_accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <td><%= account.liquid_balance %></td>
        <td><%= account.illiquid_balance %></td>
        <td><%= account.currency %></td>
        <td><%= link_to 'Account transactions', user_credit_account_path(@user, account) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Nueva cuenta de crédito', new_user_credit_account_path(@user), type: 'button', class: 'btn btn-primary' %>
</div>
<br>