config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users, only: %i[index show edit update destroy] do
    resources :debit_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
    resources :checking_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
    resources :credit_accounts, only: %i[new create show] do
      resources :transactions, only: %i[create new show]
      get :transfer, controller: :transactions
      post :create_transfer, controller: :transactions
    end
  end

  # post :liquid_installment, controller: :transactions
  post '/installments/:id' => 'installments#liquid', as: 'liquid'
  resources :categories, only: %i[index new create]
  devise_for :users, path: 'session'

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

# Transactions Controller
# rubocop:disable Metrics/ClassLength
class TransactionsController < ApplicationController
  include CurrencyControllerConcern
  before_action :set_user
  before_action :set_account
  before_action :retrieve_categories
  before_action :require_permission
  before_action :set_transfer_params, only: %i[create_transfer]

  # GET /users/:user_id/accounts/:account_id/transactions/new
  def new
    @transaction = Transaction.new
  end

  def show
    @transaction = Transaction.find_by(id: params[:id])
    @installments = @transaction.installments
  end

  # POST /users/:user_id/debit_accounts
  def create
    prepare_transaction
    save_and_redirect
  end

  # GET /users/:user_id/accounts/:account_id/transfer
  def transfer
    @url = case @account_type
           when :debit_account
             user_debit_account_create_transfer_path(@user, @account)

           when :credit_account
             user_credit_account_create_transfer_path(@user, @account)

           else
             user_checking_account_create_transfer_path(@user, @account)
           end
  end

  # POST /users/:user_id/accounts/:account_id/transfer
  def create_transfer
    unless @other_account
      return redirect_to user_checking_account_transfer_path(
        @user, @account
      ), notice: 'Accounts aren\'t valid'
    end

    @account.liquid_balance += @transfer_origin.amount
    @other_account.liquid_balance += @transfer_destination.amount

    if (@account.valid? && @transfer_origin.valid?) &&
       (@other_account.valid? && @transfer_destination.valid?)
      @account.save
      @transfer_origin.save
      @other_account.save
      @transfer_destination.save
      redirect_to [@user, @account], notice: 'Transfer successfully created.'
    else
      @account.liquid_balance += @transfer_origin.amount
      @other_account.liquid_balance -= @transfer_destination.amount
      redirect_to user_checking_account_transfer_path(
        @user, @account
      ), notice: 'Transaction isn\'t valid'
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:user_id])
  end

  # prepare transaction.
  def prepare_transaction
    @transaction = Transaction.new(transaction_params)
    @transaction.origin = @account
    @transaction.category = @category
    @amount = transaction_params[:amount].to_i * get_exchange(
      @transaction.currency, @account.currency
    )
    if @gasto_ingreso == 'GASTO'
      @transaction.amount = -@transaction.amount.abs
      if @account.instance_of? CreditAccount
        @account.illiquid_balance -= @amount
      else
        @account.liquid_balance -= @amount
      end
    else # =="INGRESO"
      @account.liquid_balance += @amount
    end
  end

  def save_and_redirect
    if @account.valid? && @transaction.valid?
      @account.save
      @transaction.save
      assign_installments
      redirect_to [@user, @account], notice: 'Transaction successfully created.'
    else
      revert_amount_on_account
      flash[:notice] = 'Transaction does not respect balance restrictions'
      render :new
    end
  end

  def assign_installments
    unit_amount = @transaction.amount.abs / @transaction.installments_qty
    module_div_amount = @transaction.amount.abs % @transaction.installments_qty
    ins = nil
    (1..@transaction.installments_qty).each do |quota_i|
      ins = Installment.create(place: quota_i, unit_amount: unit_amount,
                               liq_date: (30 * quota_i).days.from_now,
                               total_amount: @transaction.amount,
                               total_places: @transaction.installments_qty)
      @transaction.installments << ins
    end
    ins.unit_amount += module_div_amount
    ins.save
  end

  def revert_amount_on_account
    if @gasto_ingreso == 'GASTO'
      if @account.instance_of? CreditAccount
        @account.illiquid_balance += @amount
      else
        @account.liquid_balance += @amount
      end
    else # =="INGRESO"
      @account.liquid_balance -= @amount
    end
    @transaction.amount = @transaction.amount.abs
  end

  def set_account
    if params.key?('debit_account_id')
      @account_type = :debit_account
      @account = DebitAccount.find(params[:debit_account_id])

    elsif params.key?('credit_account_id')
      @account_type = :credit_account
      @account = CreditAccount.find(params[:credit_account_id])

    else # params.key?('checking_account_id') #there's no option due to routing
      @account_type = :checking_account
      @account = CheckingAccount.find(params[:checking_account_id])
    end
  end

  def set_transfer_params
    @other_account = nil
    case params[@account_type][:destination_account_type]
    when 'Debito'
      @other_account = DebitAccount
                       .find_by(id:
                        params[@account_type][:destination_account_id])

    when 'Credito'
      @other_account = CreditAccount
                       .find_by(id:
                        params[@account_type][:destination_account_id])

    else # Corriente
      @other_account = CheckingAccount
                       .find_by(id:
                        params[@account_type][:destination_account_id])
    end
    return nil unless @other_account

    @category = Category
                .find_by(id: params[@account_type][:category].to_i)

    @transfer_origin = Transaction.new
    @transfer_origin.origin = @account
    @transfer_origin.category = @category
    @transfer_origin.currency = params[@account_type][:currency]
    @transfer_origin.amount = -(params[@account_type][:amount] || 0).to_i.abs
    @transfer_origin.description = params[@account_type][:description]

    @transfer_destination = Transaction.new
    @transfer_destination.origin = @other_account
    @transfer_destination.category = @category
    @transfer_destination.currency = @other_account.currency
    @transfer_destination.amount = (params[@account_type][:amount] ||
      0).to_i.abs * get_exchange(@transfer_origin.currency,
                                 @transfer_destination.currency)
    @transfer_destination.description = params[@account_type][:description]
  end

  def retrieve_categories
    @categories = Category.all
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    @category = Category.find_by(id: params[:transaction][:category].to_i)
    @gasto_ingreso = params[:transaction][:type]
    params.require(:transaction).permit(:currency, :amount, :description,
                                        :installments_qty)
  end

  def require_permission
    is_admin = user_signed_in? && current_user.admin
    correct_user = user_signed_in? && current_user == @user
    is_owner_user = @account.user == @user
    has_permission = is_admin || (correct_user && is_owner_user)
    notice = 'You don\'t have the permissions to do that'

    redirect_to root_path, notice: notice unless has_permission
  end
end
# rubocop:enable Metrics/ClassLength

app/views/transactions/_form.html.erb
<%= form_with(model: [user, account, transaction], local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(transaction.errors.count, 'error') %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_box">

    <div class="form-group">
      <%= form.label :amount %>
      <%= form.number_field :amount, min: 1, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_field :description, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :type %>
      <%= form.select :type, %w[GASTO INGRESO], {}, { class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= form.label :currency %>
      <%= form.select :currency, %w[CLP USD], {}, { class: 'form-control' } %>
    </div>

    <div class="form-group" id="categories">
      <%= form.label :category %>
      <% @categories.each do |categoria| %>
          <label class="form-check">
            <%= form.radio_button(:category, categoria.id, id: categoria.id) %>
            <%= label_tag(:category, categoria.name) %>
          </label>
      <% end %>
    </div>

    <% if account.instance_of? CreditAccount %>
      <div class=" field ">
        <%= form.label :installments_qty %>
        <%= form.number_field :installments_qty, min: 1, class: 'form-control' %>
      </div>
    <br>
    <% end %>

    <div class=" actions ">
      <%= form.submit 'Create transaction', class: 'btn btn-primary' %>
    </div>
    <br>
  </div>
<% end %>

app/views/transactions/_transfer_form.html.erb
<%= form_with(model: [user, account], local: true, url: url, method: :post) do |form| %>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.number_field :amount, min: 1, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :destination_account_type %>
    <%= form.select :destination_account_type, %w[Debito Corriente Credito], {}, { class: 'form-control' } %>
  </div>

  <div class="form-group">
    <%= form.label :destination_account_id %>
    <%= form.number_field :destination_account_id, min: 1, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :currency %>
    <%= form.select :currency, %w[CLP USD], {}, { class: 'form-control' } %>
  </div>

    <div class="form-group" id="categories">
      <%= form.label :category %>
      <% @categories.each do |categoria| %>
          <label class="form-check">
            <%= form.radio_button(:category, categoria.id, id: categoria.id) %>
            <%= label_tag(:category, categoria.name) %>
          </label>
      <% end %>
    </div>

  <div class=" actions ">
    <%= form.submit 'Transfer', class: 'btn btn-primary' %>
  </div>
  <br>
<% end %>

app/views/transactions/new.html.erb
<h2>New transaction</h2>
<hr>

<%= render 'form', user: @user, account: @account, transaction: @transaction %>

<%= link_to 'Back', user_path(@user), type: 'button', class: 'btn btn-dark' %>
<br><br>

app/views/transactions/show.html.erb
<h1>Transaction <%= @transaction.id %> </h1>

<div>
  <h2>Transaction installments </h2>

  <table>
  <thead>
    <tr>
      <th>Posición cuota</th>
      <th>Monto cuota</th>
      <th>Fecha liquidación</th>
      <th>Status</th>
      <th>Acción</th>
    </tr>
  </thead>

  <tbody>
    <% @installments.each do |ins| %>
      <tr>
        <td><%= ins.place %>/<%= ins.total_places %></td>
        <td><%= ins.unit_amount %></td>
        <td><%= ins.liq_date %></td>
        <% if !ins.liq_status %>
            <td>Por liquidar</td>
            <td><%= link_to('Liquidar cuota', liquid_path(id: ins.id), method: :post) %></td>
        <% else %>
            <td>Liquidada</td>
            <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to('Volver a cuenta', user_credit_account_path(@account.user, @account)) %>

app/views/transactions/transfer.html.erb
<h2>New transfer</h2>
<hr>

<%= render 'transfer_form', user: @user, account: @account, transaction: @transaction, url: @url %>

<%= link_to 'Back', user_path(@user), type: 'button', class: 'btn btn-dark' %>
<br><br>